### PR TITLE
finalize news parsing

### LINKED ISSUE #1: Implement RSS Feed Parsing
* Put code into main.go (maybe create extra package)
* https://www.tum.de/?type=100

### PR DESCRIPTION
**Pull request by joschahenningsen**
closes #1

### CODE REVIEW

**Comment by joschahenningsen** [comment]
The docker container needs imagemagick, mind using something else than `from: scratch` or do you have a better idea @kordianbruck ?

**Comment by kordianbruck** [comment]
Ugh, that sounds messy and something I'd like to avoid. How about using a pure Go implementation for resizing images? https://github.com/nfnt/resize

**Comment by joschahenningsen** [comment]
Sounds good, up for a short coding session friday night to get this done? :cat2:

**Comment by kordianbruck** [comment]
Can do! After the team meeting?

**Comment by joschahenningsen** [comment]
:ok_hand:

**Pull request merged**
